# Generated by Django 5.0.1 on 2025-05-31 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_bio', models.CharField(blank=True, max_length=255, verbose_name='Kısa Tanıtım')),
                ('about', models.TextField(blank=True, verbose_name='Hakkında')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profil Resmi')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv_files/', verbose_name='CV Dosyası')),
                ('phone_number', models.CharField(blank=True, help_text='İsteğe bağlı, profilde görünecek', max_length=20, verbose_name='Telefon Numarası')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Telefon Numarası Gösterilsin Mi')),
                ('order_in_category', models.PositiveIntegerField(default=0, verbose_name='Kategori İçinde Sıralama')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='professionals.category', verbose_name='Kategori')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Profesyonel Profili',
                'verbose_name_plural': 'Profesyonel Profilleri',
                'ordering': ['category', 'order_in_category', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hizmet Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Süre (Dakika)')),
                ('meeting_type', models.CharField(choices=[('online', 'Online'), ('face_to_face', 'Yüz Yüze')], default='face_to_face', max_length=20, verbose_name='Görüşme Tipi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='professionals.professionalprofile', verbose_name='Profesyonel')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['professional', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='professionals.professionalprofile', verbose_name='Profesyonel')),
            ],
            options={
                'verbose_name': 'Çalışma Saati',
                'verbose_name_plural': 'Çalışma Saatleri',
                'ordering': ['day', 'start_time'],
                'unique_together': {('professional', 'day')},
            },
        ),
    ]
