# Generated by Django 5.0.1 on 2025-05-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şehir Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Uzman Türü')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, help_text='Örn: fas fa-user-md', max_length=100, verbose_name='İkon CSS Sınıfı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Uzman Türü',
                'verbose_name_plural': 'Uzman Türleri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Toplam profesyonel deneyim yılı', null=True, verbose_name='Deneyim Yılı'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='offers_in_person',
            field=models.BooleanField(default=True, help_text='Yüz yüze görüşme hizmeti sunuyor mu?', verbose_name='Yüz Yüze Hizmet Veriyor'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='offers_online',
            field=models.BooleanField(default=True, help_text='Online görüşme hizmeti sunuyor mu?', verbose_name='Online Hizmet Veriyor'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Yüz yüze hizmet verdiğiniz şehir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='professionals.city', verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='expert_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='professionals.experttype', verbose_name='Uzman Türü'),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Uzmanlık Dalı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('expert_types', models.ManyToManyField(help_text='Bu uzmanlık dalının hangi uzman türlerine ait olduğunu seçin', related_name='specializations', to='professionals.experttype', verbose_name='Uzman Türleri')),
            ],
            options={
                'verbose_name': 'Uzmanlık Dalı',
                'verbose_name_plural': 'Uzmanlık Dalları',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='professionals.specialization', verbose_name='Uzmanlık Dalları'),
        ),
    ]
