# Generated by Django 5.0.1 on 2025-05-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_admin_ids',
            field=models.TextField(blank=True, help_text="Virgülle ayrılmış Telegram ID'leri. Örn: 123456789,987654321", verbose_name="Telegram Yönetici ID'leri"),
        ),
    ]
